package com.example.missingpeople.repositor

enum class RussianRegion(val displayName: String, val srcName: String) {
    ALL("Вся Россия", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/iPage,"),
    ADYGEA("Адыгея", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900001"),
    ALTAI("Алтай", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900002"),
    ALTAI_REPUBLIC("Алтайский край", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900003"),
    AMUR("Амурская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900004"),
    ARKHANGELSK("Архангельская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900005"),
    ASTRACHAN("Астраханская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900006"),
    BASHKORTOSTAN("Башкортостан", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900007"),
    BELGOROD("Белгородская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900008"),
    BRUNSK("Брянская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900009"),
    BYRUT("Бурятия", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900010"),
    VLADIMIR("Владимирская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900011"),
    VOLGOGRAD("Волгоградская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900012"),
    VOLOGOTSK("Вологодская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000018"),
    VORONEZG("Воронежская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900014"),
    DAGESTAN("Дагестан", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900015"),
    EVREI("Еврейская автономная область","https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900016"),
    ZABAICAL("Забайкальский край", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900017"),
    IVANOVSK("Ивановская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900018"),
    INGYSHET("Ингушетия", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900019"),
    IRCYTSK("Иркутская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900020"),
    KABARDINOBALKARIA("Кабардино-Балкария", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900021"),
    KALININGRAD("Калининградская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900022"),
    KALMUKIA("Калмыкия", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900023"),
    KALUGA("Калужская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900024"),
    KAMCHATKA("Камчатский край", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900025"),
    KARACHAEVO("Карачаево-Черкесия", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900026"),
    KARELIA("Карелия", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900027"),
    KEMEROVO("Кемеровская область - Кузбасс", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900028"),
    KIROV("Кировская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900029"),
    KOMI("Коми", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900030"),
    KOSTROMA("Костромская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900031"),
    KRASNODAR("Краснодарский край", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900032"),
    KRASNOURSK("Красноярский край", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900033"),
    KRUM("Крым", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900034"),
    KURGAN("Курганская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900035"),
    KURSK("Курская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900036"),
    LENINGRAD("Ленинградская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900037"),
    LIPECK("Липецкая область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900038"),
    MAGADAN("Магаданская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900039"),
    MARIEL("Марий Эл", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900040"),
    MORDOVIA("Мордовия", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900041"),
    MOSCWA("Москва и М.О.", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900042"),
    MYRMANCK("Мурманская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900043"),
    NENECK("Ненецкий автономный округ", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900044"),
    NIGEGOROD("Нижегородская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900045"),
    NOVGOROD("Новгородская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900046"),
    NOVOSIBIRSK("Новосибирская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900047"),
    OMSK("Омская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900048"),
    ORENBURG("Оренбургская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900049"),
    ORLOV("Орловская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900050"),
    PENZA("Пензенская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900051"),
    PERM("Пермский край", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900052"),
    PRIMORSK("Приморский край", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900053"),
    PSKOV("Псковская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900054"),
    ROSTOV("Ростовская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900055"),
    RUZAN("Рязанская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900056"),
    SAMARA("Самарская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900057"),
    SARATOV("Саратовская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900058"),
    SAXA("Саха (Якутия)", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900059"),
    SAXALIN("Сахалинская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900060"),
    SVERDLOVSK("Свердловская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900061"),
    OSETIA("Северная Осетия", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900062"),
    SMOLENSK("Смоленская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900063"),
    STAVROPOL("Ставропольский край", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900064"),
    TAMBOVSK("Тамбовская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,8900065"),
    TATARSTAN("Татарстан", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000001"),
    TVER("Тверская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000002"),
    TOMSK("Томская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000003"),
    TYLA("Тульская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000004"),
    TIVA("Тыва", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000005"),
    TUMEN("Тюменская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000006"),
    YDMURTIA("Удмуртия", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000007"),
    YLIANOV("Ульяновская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000008"),
    XABAROVSK("Хабаровский край", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000009"),
    XAKASIA("Хакасия", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000010"),
    XANTI("Ханты-Мансийский автономный округ-Югра", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000011"),
    CHELABINSK("Челябинская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000012"),
    CHECEN("Чеченская Республика", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000013"),
    CHEVASHIA("Чувашия", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000014"),
    CHYKOTKA("Чукотский автономный округ", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000015"),
    YAMAL("Ямало-Ненецкий автономный округ", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000016"),
    YRAROSLAV("Ярославская область", "https://поисковая-база.рф/search/sOrder,dt_pub_date/iOrderType,desc/category,9/country,RU/region,1000017");

    companion object {
        fun getSortedRegions(): List<RussianRegion> {
            return values()
                .filter { it != ALL } // Исключаем "Всю Россию" из общего списка
                .sortedBy { it.displayName } // Сортировка по алфавиту
        }
    }
}